replicaCount: 1

image:
  repository: transfers
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

probes:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
