spring:
  application.name: gateway
  cloud.gateway.routes:
    - id: accounts-route
      uri: http://accounts
      predicates:
        - Path=/accounts/**
    - id: cash-route
      uri: http://cash
      predicates:
        - Path=/cash/**
    - id: transfers-route
      uri: http://transfers
      predicates:
        - Path=/transfers/**
