apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.global.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.secrets.keycloak.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.keycloak.admin.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bank-ui-secret
type: Opaque
stringData:
  KEYCLOAK_BANK_UI_CLIENT_ID: {{ .Values.secrets.bankUi.keycloak.clientId | quote }}
  KEYCLOAK_BANK_UI_CLIENT_SECRET: {{ .Values.secrets.bankUi.keycloak.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cash-secret
type: Opaque
stringData:
  KEYCLOAK_CASH_CLIENT_ID: {{ .Values.secrets.cash.keycloak.clientId | quote }}
  KEYCLOAK_CASH_CLIENT_SECRET: {{ .Values.secrets.cash.keycloak.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: transfers-secret
type: Opaque
stringData:
  KEYCLOAK_TRANSFERS_CLIENT_ID: {{ .Values.secrets.transfers.keycloak.clientId | quote }}
  KEYCLOAK_TRANSFERS_CLIENT_SECRET: {{ .Values.secrets.transfers.keycloak.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: accounts-secret
type: Opaque
stringData:
  KEYCLOAK_ACCOUNTS_CLIENT_ID: {{ .Values.secrets.accounts.keycloak.clientId | quote }}
  KEYCLOAK_ACCOUNTS_CLIENT_SECRET: {{ .Values.secrets.accounts.keycloak.clientSecret | quote }}
