server.port: ${SERVER_PORT:8080}

management.endpoints.web.exposure.include: health

keycloak:
  realm: ${KEYCLOAK_BANK_REALM:bank}
  base-url: ${KEYCLOAK_BASE_URL:http://host.docker.internal:8083}
  issuer-uri: ${KEYCLOAK_ISSUER_URI:${keycloak.base-url}/realms/${keycloak.realm}}

spring:
  application.name: bank-ui
  security.oauth2.client:
    provider.keycloak:
      issuer-uri: ${keycloak.issuer-uri}
    registration.keycloak:
      provider: keycloak
      client-id: ${KEYCLOAK_BANK_UI_CLIENT_ID:bank-ui}
      client-secret: ${KEYCLOAK_BANK_UI_CLIENT_SECRET:bank-ui-secret}
      client-name: Keycloak
      authorization-grant-type: authorization_code
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      scope: openid, profile

integration:
  accounts.base-url: ${ACCOUNTS_BASE_URL:http://gateway:8084/accounts}
  cash.base-url: ${CASH_BASE_URL:http://gateway:8084/cash}
  transfers.base-url: ${TRANSFERS_BASE_URL:http://gateway:8084/transfers}
