management.endpoints.web.exposure.include: health

spring:
  application.name: gateway
  cloud.gateway.routes:
    - id: accounts-route
      uri: http://accounts:8080
      predicates:
        - Path=/accounts/**
    - id: cash-route
      uri: http://cash:8080
      predicates:
        - Path=/cash/**
    - id: transfers-route
      uri: http://transfers:8080
      predicates:
        - Path=/transfers/**
