server.port: ${SERVER_PORT:8084}

management.endpoints.web.exposure.include: health

spring:
  application.name: gateway
  cloud.gateway.routes:
    - id: accounts-route
      uri: http://accounts:8085
      predicates:
        - Path=/accounts/**
    - id: cash-route
      uri: http://cash:8086
      predicates:
        - Path=/cash/**
    - id: transfers-route
      uri: http://transfers:8087
      predicates:
        - Path=/transfers/**
