management.endpoints.web.exposure.include: health

keycloak:
  realm: ${KEYCLOAK_BANK_REALM:bank}
  base-url: ${KEYCLOAK_BASE_URL:http://host.docker.internal:8083}
  issuer-uri: ${KEYCLOAK_ISSUER_URI:${keycloak.base-url}/realms/${keycloak.realm}}

spring:
  application.name: cash
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa.hibernate.ddl-auto: validate
  sql.init.mode: never  # never, always
  security.oauth2:
    resourceserver.jwt.issuer-uri: ${keycloak.issuer-uri}
    client:
      provider.keycloak:
        issuer-uri: ${keycloak.issuer-uri}
      registration.cash:
        provider: keycloak
        authorization-grant-type: client_credentials
        client-id: ${KEYCLOAK_CASH_CLIENT_ID:cash}
        client-secret: ${KEYCLOAK_CASH_CLIENT_SECRET:cash-secret}

integration:
  accounts.base-url: ${ACCOUNTS_BASE_URL:http://accounts:8080/accounts}
  notifications.base-url: ${NOTIFICATIONS_BASE_URL:http://notifications:8080/notifications}

cash:
  retry:
    fixed-delay-ms: 5000
    batch-size: 50
  notifications:
    fixed-delay-ms: 5000
    batch-size: 50
  cleanup:
    cron: 0 0 12 * * *
    batch-size: 500
