{{- range $name, $service := .Values.services }}
{{- $serviceConfig := default dict $service.service }}
{{- $serviceType := default $.Values.defaults.service.type $serviceConfig.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: {{ $serviceType }}
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: {{ default $.Values.defaults.service.port $serviceConfig.port }}
      targetPort: {{ default $.Values.defaults.service.targetPort $serviceConfig.targetPort }}
{{- if eq $serviceType "NodePort" }}
      nodePort: {{ index $.Values.global.nodePorts $serviceConfig.nodePortKey }}
{{- end }}
{{- end }}
