spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa.hibernate.ddl-auto: validate
  sql.init.mode: never  # never, always
  security.oauth2:
    resourceserver.jwt.issuer-uri: ${keycloak.issuer-uri}

integration:
  accounts.base-url: ${ACCOUNTS_BASE_URL:http://accounts/accounts}
