secrets:
  keycloak:
    admin:
      username: admin
      password: admin
  postgres:
    user: user
    password: password
  bankUi:
    keycloak:
      clientId: bank-ui
      clientSecret: bank-ui-secret
  cash:
    keycloak:
      clientId: cash
      clientSecret: cash-secret
  transfers:
    keycloak:
      clientId: transfers
      clientSecret: transfers-secret
  accounts:
    keycloak:
      clientId: accounts
      clientSecret: accounts-secret
