management.endpoints.web.exposure.include: health

keycloak:
  realm: ${KEYCLOAK_BANK_REALM:bank}
  base-url: ${KEYCLOAK_BASE_URL:http://host.docker.internal:8083}
  issuer-uri: ${KEYCLOAK_ISSUER_URI:${keycloak.base-url}/realms/${keycloak.realm}}

spring:
  application.name: notifications
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa.hibernate.ddl-auto: validate
  sql.init.mode: never  # never, always
  security.oauth2:
    resourceserver.jwt.issuer-uri: ${keycloak.issuer-uri}

notifications:
  cleanup:
    cron: 0 0 12 * * *
    batch-size: 500
